name: Steven D. Shelton
favicon: null
layout_spectrum: 0.7503
typography_spectrum: 0.98616
title: Steven D. Shelton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-9727133-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ae9e84'
    - '#191410'
    - '#874e3a'
    - '#898083'
    - '#9e6a5c'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
