typography_spectrum: 0.98616
color:
  brandColors:
    - '#ae9e84'
    - '#191410'
    - '#874e3a'
    - '#898083'
    - '#9e6a5c'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-9727133-1
  facebook: null
  twitter: null
name: Steven D. Shelton
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The Shape of Love
    id: df388971-7b95-4e92-a84f-eed67766b442
    type: content
favicon: null
title: Steven D. Shelton
purpose: []
