name: Steven D. Shelton
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2504
title: Things done to pass the time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-9727133-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f7d5c'
    - '#0f110c'
    - '#c8ccbb'
    - '#fc5426'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
